version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the code"
      - npm install
      - npm run build

artifacts:
  files:
    - "**/*" # 指定编译后的文件
  base-directory: build # 指定编译产物所在的目录

post_build:
  commands:
    - echo "Uploading build to S3"
    - aws s3 sync build/ s3://red2.fun --delete # 上传到 S3
